# Generated by Django 5.0.1 on 2024-01-26 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_product_ingredients_product_weight_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredients',
            old_name='product_weight',
            new_name='product',
        ),
        migrations.AddField(
            model_name='ingredients',
            name='weight',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
