# Generated by Django 5.0.1 on 2024-01-26 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_product_weight_ingredients_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='product',
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='weight',
            field=models.CharField(max_length=250),
        ),
    ]
