# Generated by Django 5.0.1 on 2024-01-26 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_recipe_product_alter_ingredients_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='products',
            field=models.ManyToManyField(to='myapp.product'),
        ),
    ]
