# Generated by Django 5.0.1 on 2024-01-26 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_recipe_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='products',
            new_name='product',
        ),
        migrations.RemoveField(
            model_name='ingredients',
            name='weight',
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_weight', models.IntegerField()),
                ('product_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.product')),
            ],
        ),
        migrations.AddField(
            model_name='ingredients',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.order'),
            preserve_default=False,
        ),
    ]
