# Generated by Django 5.0.1 on 2024-01-26 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_rename_products_recipe_product_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredients',
            options={'verbose_name': 'Ингридиент', 'verbose_name_plural': 'Ингридиенты'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Входящий продукт', 'verbose_name_plural': 'Входящие продукты'},
        ),
        migrations.RemoveField(
            model_name='ingredients',
            name='order',
        ),
        migrations.RemoveField(
            model_name='ingredients',
            name='product',
        ),
        migrations.AddField(
            model_name='ingredients',
            name='order',
            field=models.ManyToManyField(to='myapp.order'),
        ),
        migrations.AddField(
            model_name='ingredients',
            name='product',
            field=models.ManyToManyField(to='myapp.product'),
        ),
    ]
