# Generated by Django 5.0.1 on 2024-01-26 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_remove_order_product_name_remove_recipe_product_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='added_amount',
            new_name='using_count',
        ),
    ]
